# from https://github.com/confluentinc/cp-all-in-one/tree/7.5.0-post/cp-all-in-one-community
---
services:
  doctoboot-playground_postgres:
    image: postgres:15.5
    ports:
      - '127.0.0.1:55432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${USER}']
      interval: 2s
      timeout: 2s
      retries: 20
    restart: unless-stopped

volumes:
  postgres_data:
