name: Dependency Submission

on:
  push:
    branches:
      - main
    paths:
      - '**/pom.xml'
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: prod-linux-s

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java JDK
      uses: doctolib/actions/setup-java@setup-java-v0.1.3
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'

    - name: Submit Maven Dependencies
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
